### ISSUE TITLE
TODO Milestone #2

### ISSUE THREAD

**Issue by es2812** [es2812/AgoraChain#1]
List of TODO for Milestone #2 (due December 25th):

- [x] Implement Representation restrictions.
- [ ] Update the diagrams in `README.md`
- [x] Decide and set access and privacy settings (vía the `permissions.acl` file).
- [ ] Look into private channels/identity mixer. Specially in the transaction/assets related to Secret Voting.
-  [x] See what we can do about IDs. IDs should be UUID (and avoid giving away certain data in some cases) but transaction functions cannot set non-deterministic data. Some options are:
    1. **Generate them client-side.** Would make them depend on API implementation.
    2. **Let user input them.** Insecure, can't guarantee uniqueness.
    3. **Use hashing of deterministic values in server-side.** Probably the best option, would have to find a way to implement hashing in transaction function (Hyperledger doesn't allow `include` in chaincode).
