### ISSUE TITLE
TODO Milestone #3

### ISSUE THREAD

**Issue by es2812** [es2812/AgoraChain#2]
List of TODOs for Milestone #3 Finish API (due January 2nd 2019)

- [x] Create angular project.
- [x] Update README to reflect angular API usage.
- [x] Handle errors (permissions) more elegantly.
- [x] Modify transaction forms to restrict to valid options.
- [x] Restrict transactions for only allowed types.
- [ ] Change login page.
- [ ] Look into events for:
  - Notify Participants of new elections.
  - Notify represented citizens of their Politician creating or updating their vote.
  - Notify Participants of opening of elections.
  - Notifiy Participants of the closing and results of elections.
- [ ] Look into persistent storage.
